name: Test, Build, and Push to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - "main"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          python -m pip install -r src/requirements.txt
      - name: Run tests
        env:
          MODE: "github actions"
        run: |
          pytest src/tests.py
  build_deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Build container image
        run: |
          docker build -f Dockerfile -t mohaseb-test .
          docker tag mohaseb-test ${{secrets.CONTAINER_IMAGE_URL}}:latest
          gcloud auth configure-docker ${{secrets.GCLOUD_REGION}}-docker.pkg.dev
          docker push us-central1-docker.pkg.dev/mohaseb-app/mohaseb-test-repo/mohaseb-test:latest
      - name: Deploy container to Cloud Run
        run: |
          - gcloud run deploy mohaseb-test-run \
          --image=${{secrets.CONTAINER_IMAGE_URL}}:latest \
          --allow-unauthenticated \
          --region=${{secrets.GCLOUD_REGION}} \
          --project=${{secrets.GCLOUD_PROJECT_ID}}