name: Test, Build, and Push to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - "main"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          python -m pip install -r src/requirements.txt
      - name: Run tests
        env:
          MODE: "github actions"
        run: |
          pytest src/tests.py
  build_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        run: |
          docker build -f Dockerfile -t mohaseb-test .
          docker tag mohaseb-test us-central1-docker.pkg.dev/mohaseb-app/mohaseb-test-repo/mohaseb-test:latest
          docker push us-central1-docker.pkg.dev/mohaseb-app/mohaseb-test-repo/mohaseb-test:latest